# Generated by Django 3.0.4 on 2020-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('segundo_nome', models.CharField(max_length=200)),
                ('ultimo_nome', models.CharField(max_length=200)),
                ('sou_1', models.CharField(max_length=200)),
                ('sou_2', models.CharField(max_length=200)),
                ('sou_3', models.CharField(max_length=200)),
            ],
        ),
    ]
