# Generated by Django 3.0.4 on 2020-03-30 21:40

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200330_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preiodo', models.CharField(max_length=200)),
                ('titulo', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preiodo', models.CharField(max_length=200)),
                ('titulo', models.TextField()),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.CharField(max_length=200)),
                ('nivel_habilidade', index.models.IntegerRangeField()),
                ('nivel_teorico', index.models.IntegerRangeField()),
                ('nivel_pratico', index.models.IntegerRangeField()),
                ('prioridade', models.CharField(choices=[('principal', 'principal'), ('secundaria', 'secundaria')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
