# Generated by Django 3.0.4 on 2020-03-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_educacao_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educacao',
            old_name='preiodo',
            new_name='periodo',
        ),
    ]
