# Generated by Django 3.0.4 on 2020-03-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200330_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil_base',
            field=models.TextField(default='', max_length=999999),
            preserve_default=False,
        ),
    ]
