# Generated by Django 3.0.4 on 2020-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200330_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('url', models.URLField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('fimagem_base', models.TextField(blank=True, max_length=999999, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil_base',
            field=models.TextField(blank=True, max_length=999999, null=True),
        ),
    ]
