# Generated by Django 3.0.4 on 2020-03-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_case_data_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='curriculo_base',
            field=models.TextField(blank=True, max_length=999999, null=True),
        ),
    ]
