# Generated by Django 3.0.5 on 2020-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_perfil_curriculo_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Github'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Instagram'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Linkedin'),
        ),
    ]
